spring:
  datasource:
    url: "jdbc:postgresql://${REST_SERVER_DB_HOST}:${REST_SERVER_DB_PORT}/${REST_SERVER_DB_NAME}"
    username: ${REST_SERVER_DB_LOGIN}
    password: ${REST_SERVER_DB_PASS}
    driver-class-name: org.postgresql.Driver

  application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 86400000 # 24 hours
